spring:
  application:
    name: incidentflow
  datasource:
    url: jdbc:postgresql://localhost:5432/incidentflow
    username: incidentflow
    password: incidentflow
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
